{ config, pkgs, lib, ... }:

{
  # Pull in hardware config generated by the installer
  imports = [ ./hardware-configuration.nix ];

  #  Boot loader 
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  #  Networking & identity 
  networking.hostName = "nixos";
  networking.firewall.allowedTCPPorts = [ 22 ];

  #  Locale & time 
  time.timeZone     = "Europe/Helsinki";
  i18n.defaultLocale = "fi_FI.UTF-8";
  console.keyMap    = "fi";

  #  User account 
  users.users.topi = {
    isNormalUser = true;
    description  = "Topi";
    extraGroups  = [ "wheel" "networkmanager" ];   # sudo + nmcli
    hashedPassword = "$$6$zZUIDTir1fhMbAZG$iUzDUV03./jyA/WwZI8hi4xuq4ZuBxp30Xptr1eycuNI8dt8TV1z0Eyl8Pdy0zHOM29mcn/2oE.tIIfx4GnW30";
  };

  #  OpenSSH server 
  services.openssh.enable = true;
  services.openssh.settings = {
    PermitRootLogin = "no";
    PasswordAuthentication = true;  # set to true if you set hashedPassword
  };

  #  Useful base packages 
  environment.systemPackages = with pkgs; [ vim git zsh neovim ];

  #  Misc 
  programs.ssh.startAgent = true;   # convenience for local logins

  # Required: keep at the version you installed from
  system.stateVersion = "24.11";    # adjust if you install a different release
}
